"""phase2_data_models

Revision ID: 5977d78024ff
Revises: fdc2a4bcecca
Create Date: 2026-06-10 10:37:37.094390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5977d78024ff'
down_revision: Union[str, None] = 'fdc2a4bcecca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='webhookeventstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=True)
    op.create_table('git_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('github_app_installation_id', sa.String(length=100), nullable=False),
    sa.Column('repo_full_name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_git_integrations_github_app_installation_id'), 'git_integrations', ['github_app_installation_id'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'routed', 'active', 'in_discussion', 'consensus_reached', 'plan_review', 'agent_working', 'in_review', 'split', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('source', sa.Enum('synapse', 'github', name='ticketsource'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='ticketpriority'), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_author_login', sa.String(length=100), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=True),
    sa.Column('parent_ticket_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_channel_id'), 'tickets', ['channel_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('human', 'system', 'approval_card', 'plan_card', 'blocker_card', name='messagetype'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False)
    op.create_table('thread_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('structured_state_json', sa.JSON(), nullable=True),
    sa.Column('last_processed_message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_processed_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.drop_column('projects', 'default_branch')
    op.drop_column('projects', 'github_app_installation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_app_installation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('default_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('thread_states')
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tickets_channel_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_git_integrations_github_app_installation_id'), table_name='git_integrations')
    op.drop_table('git_integrations')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
