"""add skills and agent runs

Revision ID: 88721a7f7de5
Revises: e56e2083dc8c
Create Date: 2026-07-10 20:25:35.883800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88721a7f7de5'
down_revision: Union[str, None] = 'e56e2083dc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Enum('specialty', 'technology', name='skilldimension'), nullable=False),
    sa.Column('discipline', postgresql.ENUM('frontend', 'backend', 'database', 'devops', 'infrastructure', 'mobile', 'security', 'qa_testing', 'data_engineering', 'ai_ml', 'blockchain', 'embedded', 'desktop', 'platform_sdk', 'technical_writing', name='channeldiscipline', create_type=False), nullable=True),
    sa.Column('file_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dimension', 'discipline', name='uq_skill_files_workspace_dimension_discipline')
    )
    op.create_index(op.f('ix_skill_files_workspace_id'), 'skill_files', ['workspace_id'], unique=False)
    op.create_table('skill_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('specialty_file_id', sa.String(), nullable=True),
    sa.Column('technology_file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_file_id'], ['skill_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technology_file_id'], ['skill_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_assignments_channel_id'), 'skill_assignments', ['channel_id'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'awaiting_review', 'approved', 'rejected', 'failed', name='agentrunstatus'), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('checkpoint_state_json', sa.JSON(), nullable=True),
    sa.Column('edited_by_user_id', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_ticket_id'), 'agent_runs', ['ticket_id'], unique=False)
    op.create_index('uq_agent_runs_ticket_active', 'agent_runs', ['ticket_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('agent_run_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='agentrunstepstatus'), nullable=False),
    sa.Column('model_prompt', sa.Text(), nullable=True),
    sa.Column('model_response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_agent_run_id'), 'agent_run_steps', ['agent_run_id'], unique=False)
    op.add_column('git_integrations', sa.Column('last_ingested_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_integrations', 'last_ingested_sha')
    op.drop_index(op.f('ix_agent_run_steps_agent_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index('uq_agent_runs_ticket_active', table_name='agent_runs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_agent_runs_ticket_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_skill_assignments_channel_id'), table_name='skill_assignments')
    op.drop_table('skill_assignments')
    op.drop_index(op.f('ix_skill_files_workspace_id'), table_name='skill_files')
    op.drop_table('skill_files')
    # ### end Alembic commands ###
