"""make_github_app_installation_id_non_unique

Revision ID: e56e2083dc8c
Revises: 5977d78024ff
Create Date: 2026-06-16 09:07:17.234830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56e2083dc8c'
down_revision: Union[str, None] = '5977d78024ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_git_integrations_github_app_installation_id', table_name='git_integrations')
    op.create_index(op.f('ix_git_integrations_github_app_installation_id'), 'git_integrations', ['github_app_installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_integrations_github_app_installation_id'), table_name='git_integrations')
    op.create_index('ix_git_integrations_github_app_installation_id', 'git_integrations', ['github_app_installation_id'], unique=True)
    # ### end Alembic commands ###
