"""add workspace invite fk constraints

Revision ID: fb9fc3163ba4
Revises: 5fe61f68510b
Create Date: 2026-05-28 11:51:24.296410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9fc3163ba4'
down_revision: Union[str, None] = '5fe61f68510b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'workspace_invites', 'channels', ['channel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workspace_invites', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_invites', type_='foreignkey')
    op.drop_constraint(None, 'workspace_invites', type_='foreignkey')
    # ### end Alembic commands ###
