"""add_the_git_provider

Revision ID: fc9219f3e60f
Revises: 18bcd787d7d8
Create Date: 2026-08-06 19:28:16.642061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9219f3e60f'
down_revision: Union[str, None] = '18bcd787d7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_integrations', sa.Column('provider', sa.String(length=50), server_default='github', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_integrations', 'provider')
    # ### end Alembic commands ###
